devshr: initial import of devshr from 9front
Harvey-OS/harvey pull request #1122
Opened 2021-05-01 10:39 UTC by gmacd

added mit license to top of file, with 20XX changed to 2021

Signed-off-by: Graham MacDonald <grahamamacdonald@gmail.com>

2021-05-01 16:24 UTC, fhs approved these changes

2021-05-04 18:52 UTC, rminnich approved these changes

2021-05-04 18:57 UTC, rminnich requested changes

2021-05-04 18:57 UTC, rminnich commented on sys/src/9/port/devshr.c
> +	c0 = mntattach(bc, nil, aname, 0);
I think it has to be
mntattachversion(bc, "9P2000", aname, 0);
right?

2021-05-05 22:24 UTC, gmacd commented
I think it would be best to commit this as is, in its unmodified form.  This will then make it easier to review the changes required to get it to build and run in harvey.

2021-05-07 02:43 UTC, rminnich approved these changes

2021-05-07 05:53 UTC, merged